### ISSUE TITLE
Pensar acciones de anulación

### ISSUE THREAD

**Issue by fdodino** [marchionne-lattenero/seguimiento#2]
Una anulación puede generar un movimiento de anulación en el log de Ordenes:
- Anulación de cocinar: suma al stock de pendientes
- Anulación de pedido: resta al stock de pendientes

Se visualizará en el Caso de Uso Órdenes:
- Fecha
- -1 / +1 según corresponda
- Usuario
- Producto

**Comment by cdmarchionne** [comment]
DONE
